name : "multi event pipeline/workflow"

on:
  push:
    branches:
      - master
      - studentdevelopment
  pull_request:
    branches:
      - master
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name : "print multiple event"
        run: echo "print details"

  on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: "running on pull request"
        run: echo "running on pull request"
